### ISSUE TITLE
Optimizr

### ISSUE THREAD

**Issue by artlogic** [artlogic/arsmentis#32]
I'd like you to run the site through this: http://optimizr.com/

I imagine they will try and get you to buy something, but I thought it might be helpful to you. It's not terribly urgent, so I marked it post launch, but you can use http://arsmentis.com/new/ if you like.

**Comment by artlogic** [comment]
What does this say now?

**Comment by SKBruck** [comment]
Last Crawl was on Dec. 15, same issues as before.

**Comment by artlogic** [comment]
How do we get it to recrawl. The site wasn't deployed then.

**Comment by SKBruck** [comment]
I think we have to wait for it to re-crawl the site in 3 days. Or, I can delete the account and start over.

**Comment by artlogic** [comment]
That's fine. Can you set a reminder to check it then?

**Comment by SKBruck** [comment]
I can, yes - I've got it in my phone so it'll alarm me

**Comment by SKBruck** [comment]
I just checked again, and it's got the next crawl set to 11 hours from now - which is around midnight.

**Comment by SKBruck** [comment]
I checked optimizr today and it had all the same warnings and issues, so I deleted that project and re-signed up with arsmentis.com (rather than arsmentis.com/new). We now have the following:

Errors: 

* Faulty 404-Page - Pages that are not available on the server return an incorrect status-code.

Warnings:

* Multiple use for H1 - A H1 heading has been used multiple times per page. This tag may only be used once per document.
* Very few Pages - The project is made up of only a few indexable pages. Additional content can increase the visibility.

Notices:

* Internal Redirects - Internal links are set to 301/302-redirects. This will likely cause part of the link's strength to go to waste.

**Comment by artlogic** [comment]
I'll fix the 404.  Did it mention where it found the 301/302 problems?

Can you look at the H1 situation?

**Comment by SKBruck** [comment]
The h1 issue is on each page, and I am about 99% sure it's because the logo is encased in an h1, and so are the titles of the pages. I'm not yet certain how to fix it.

The 301/302 errors are on all of the pages, with duplicate errors on the about, contact, and clients page, which leads me to suspect it has something to do with the {{ root_url }} stuff. Only links with that have 301/302 errors. I have no idea what that means though.

**Comment by artlogic** [comment]
How can I see the report?

- James

**Comment by artlogic** [comment]
Most of the 301s are OK, but this is happening:

URL from 	https://www.arsmentis.com/services
URL to 	http://www.arsmentis.com/services/
HTTP-Code 	301

Which needs to stop.  This is also me.

**Comment by artlogic** [comment]
The 404 issue is that http 404s cause redirects to https 404s... not sure what the best practice is here, so I'll look into it.

**Comment by SKBruck** [comment]
Update on the h1 issue: I'm almost certainly going to be able to fix it soon. I can easily remove the h1 but the css gets messed up, and while I'm certain it's a much easier-to-fix issue that I'm currently make it, I can't seem to figure out how to fix it. There's a lot of different h1 styles. On the plus side, I think this will also solve issue #28 - so that's good.

**Comment by artlogic** [comment]
Keep at it, but if you can't resolve this until you re-make the theme to be simpler, then so be it.

**Comment by SKBruck** [comment]
I'm planning to see if giving the h1's ids might help. I am just not figuring this out, and I think identifying them will help me. I have been experimenting with making the theme simpler whenever I get frustrated.

**Comment by SKBruck** [comment]
Finally got into the account and I think I've fixed the issue with signing in so I should be able to update you when it crawls.

At the most recent crawl results: 1 error (faulty 404 page), 1 warning (too few pages), and 9 301/302 redirect errors.

Would you like me to make specific issues for you for the 404 error and redirect errors?

**Comment by SKBruck** [comment]
New crawl today:

Errors: faulty 404
Warnings: Slow load time, too few pages
Notices: 301/302 redirect errors

This is the new error: 
Excessive Load-Times
The page is taking longer than 5 seconds to load. Long load-times can be a reason for visitors or the Google-crawler to bail on you.

**Comment by artlogic** [comment]
Hmmm - may have been a problem with NFSN - let me know if it continues.

- James

**Comment by SKBruck** [comment]
I will - the next crawl is in 6 days.

I signed in to see if I could get more information. It states that arsmentis.com/contact/  took 7 seconds to load. No other urls were included.

**Comment by artlogic** [comment]
Pretty much got to be a problem with NSFN - what day/time?

- James

**Comment by SKBruck** [comment]
Yesterday around 9 pm - last crawl was 22 hours ago.

**Comment by SKBruck** [comment]
Excessive load time error is gone. It only emails me monthly, apparently.

**Comment by SKBruck** [comment]
I am adding this to Phase 2, mostly because I think the faulty 404 and 301/302 redirects will be fixed when I remake the site, and I wanted to let you know what's going on.

**Comment by artlogic** [comment]
No - the faulty redirects are due to the mod_rewrite stuff in the .htaccess - probably something I need to take care of unless you care to learn a lot more about what's going on. Why don't you make another issue just for the fault redirects and assign it to me.

**Comment by SKBruck** [comment]
I wouldn't mind learning more about it, but I'm not sure where to start, so if you want it fixed soonish it's probably better for you to handle it. I'll make an issue and assign it to you.

Do you want to keep this issue open and have me continue to update you on optimizr crawls, or would you rather I close this and then if a crawl picks up something new, make a new issue to let you know about it?

**Comment by artlogic** [comment]
Let's close it.
